package pojos;
// Generated 29/10/2018 11:42:52 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codigo;
     private String usuario;
     private String password;
     private Character tipo;

    public Usuario() {
    }

	
    public Usuario(int codigo) {
        this.codigo = codigo;
    }
    public Usuario(int codigo, String usuario, String password, Character tipo) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.password = password;
       this.tipo = tipo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }




}


